### PR TITLE
Generation overhaul

### PR DESCRIPTION
**Pull request by veprogames**
The underground is not full of ores anymore, so you have to search for them and not just dig straight down. Bedrock and Magma spawn earlier.

### CODE REVIEW

**Comment by veprogames** [comment]
When the Ore Generation is ok like this, #14 can be included in here, a bit of height variation and maybe some grass plants

**Comment by veprogames** [comment]
image

this is how it looks like with perlin noise, height variation can be tweaked

**Comment by veprogames** [comment]
Plants (for decoration) and Extreme Hills experiment

image
image

**Comment by veprogames** [comment]
Right now, Plants will stay in air when breaking the block below though...

**Comment by Skamiz** [comment]
You can add the 'attached_node' group to the plants to make them disappear, when the node under them is dug.
I played for a bit in this version and would say it's good to go.
It's still possible to skip pickaxe tiers, but since you now have to dig through the harder stone to get to the material it's almost not worth it. Instead the random higher tier ores are much more valuable, because the more of them you get the less you have to mine for them later. This creates an interesting balancing act between going deep enough for the mineral you want to start appearing, but staying high enough to be able to dig fast through the softer stone.

Long term it might be good to have a visual indicator that the stone is getting harder. Even if it's just a very gradual shift in color. Currently I am relying a lot on the debug hud to see the nodes names to figure out their tiers.

**Comment by veprogames** [comment]
Will add that, and then merge. Is there a quick way to make the sunflower scale {x = 1, y = 2, z = 1}? right now, it's {x = 2, y = 2, z = 2}, which makes them looked stretched. (the texture is 32x64)

**Comment by Skamiz** [comment]
I think the easiest way is to make the texture 64x64 with empty space on the left and right.

**Pull request merged**
