### PR TITLE
Track highest Mineral level and congratulate the Player

### PR DESCRIPTION
**Pull request by veprogames**
- announce when a player reaches a new mineral tier
- message when mining the last mineral
- congratulation message when mining the last mineral

there's still a problem: I return true in on_dig, but the mineral can't be broken anymore

if the welcome message is sufficient I'd remove the TODO comment

### CODE REVIEW

**Comment by veprogames** [comment]
oh yea, minetest.remove_node would fix it, but is that the correct way?

**Comment by Skamiz** [comment]
it is, but if you don't want to deal with the node breaking at all, you can also move your code to 'after_dig_node' instead

**Comment by veprogames** [comment]
this works, thanks! I'd merge this if there's nothing missing. Should the TODO comment be removed or should it stay?

**Comment by Skamiz** [comment]
Feel free to remove it.

**Pull request merged**
