### PR TITLE
Rebalance

### PR DESCRIPTION
**Pull request by veprogames**
* First 2 Light Blocks are brighter
* Light Blocks have their own breaking times (hyperbolic - exponential is harder to balance here), should it by hyperbolic or exponential?

### CODE REVIEW

**Comment by veprogames** [comment]
I need feedback if there's something unbalanced

**Comment by Skamiz** [comment]
Sorry, didn't realize you were waiting on me. I think the coal light can get down as low as 6 without getting annoying to use.

**Comment by veprogames** [comment]
I'll do 7, that's still pretty dark

**Comment by veprogames** [comment]
(resolved merge conflict)

**Pull request merged**
